title: "Will Schneider — Data Science Portfolio"
description: "Portfolio of projects in predictive modeling, analytics, and machine learning"

remote_theme: "mmistakes/minimal-mistakes"   # pulls the theme

url: "https://schwill2018.github.io"         # for canonical links
baseurl: ""                                  # user/org site → leave empty

plugins:                                     # all allowed by GitHub Pages
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

# make everything in _pages render at /<filename>/
collections:
  pages:
    output: true
    permalink: /:path/

# default layout for pages/posts
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
  - scope:
      path: ""
      type: posts
    values:
      layout: single
