title: "Will Schneider — Data Science Portfolio"
description: "Portfolio of projects in predictive modeling, analytics, and machine learning"
theme: jekyll-theme-primer
logo: 
show_downloads: false
google_analytics: 
# Navigation links
navigation:
  - title: "Home"
    url: /
  - title: "Projects"
    url: /projects
  - title: "Blog"
    url: /blog
  - title: "Contact"
    url: /contact

# Include assets (custom css)
defaults:
  - scope:
      path: "assets"
    values:
      sitemap: false
sass:
  style: compressed

# Custom CSS
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Optional: highlight Brookwater Labs blue
# See assets/custom.css for easy color swap
