title: Will Schneider
tagline: Data Science Portfolio
url: https://schwill2018.github.io
baseurl: ""   # keep empty for user site

remote_theme: cotes2020/jekyll-theme-chirpy

lang: en
timezone: America/Chicago

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Chirpy options
theme_mode: light
paginate: 10
paginate_path: page:num
toc: true

# Social
social:
  name: Will Schneider
  email: will@brookwaterlabs.com
  links:
    - https://github.com/schwill2018
    - https://www.linkedin.com/in/willschneider214
# Analytics (optional)
google_site_verification: google49f59bdc284310ae
# google_analytics:
#   id: G-XXXXXX

# Permalinks
permalink: /:categories/:title/

# Feed and sitemap
feed:
  path: atom.xml

defaults:
  - scope: { path: "" }
    values:
      layout: post
      author: "Will Schneider"
